spring:
  application:
    name: devflow-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/devflow
    username: postgres
    password: 89327934

  jpa:
    hibernate:
      ddl-auto: none

    open-in-view: false

    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    org.springframework.security: INFO
    org.hibernate.SQL: DEBUG